version: '2'

services:
  datastore:
    image: drupal_datastore_prod
    build: .
    volumes:
      - /var/www/html

  db:
    image: drupal_db_prod
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  php:
    image: drupal_php_prod
    build: ./php
    volumes_from:
      - datastore

  web:
    image: drupal_web_prod
    build: ./nginx
    volumes_from:
      - datastore
    ports:
      - "80:80"
